"""
Django settings for adoption_service project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!e^$%sa!34yzt^+3orbinabf4@n+b&8-w^+ly5$sm@ff6evkuo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'adoption',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.security.SecurityMiddleware",
]

ROOT_URLCONF = 'adoption_service.urls'
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
       "DIRS": [
            BASE_DIR / "../ui_service/templates",
        ],  
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adoption_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os
from pathlib import Path
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "../ui_service/static",  # shared UI files
    BASE_DIR / "static",                # local microservice static
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

RABBITMQ = {
'HOST': os.environ.get('RABBITMQ_HOST', 'rabbitmq'),
'PORT': int(os.environ.get('RABBITMQ_PORT', 5672)),
'USER': os.environ.get('RABBITMQ_USER', 'guest'),
'PASSWORD': os.environ.get('RABBITMQ_PASSWORD', 'guest'),
'EXCHANGE': os.environ.get('RABBITMQ_EXCHANGE', 'adoption_exchange'),
}


# Consul
CONSUL_HOST = os.environ.get('CONSUL_HOST', 'consul')
CONSUL_PORT = int(os.environ.get('CONSUL_PORT', 8500))



# ...
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'adoption.authentication.StatelessJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# Simple JWT Configuration (for verification of signing key)
# We must use the SAME secret key as accounts_service or configure RS256. 
# Assuming symmetric HS256 with same SECRET_KEY across services for simplicity in this student project,
# OR we need to know how they share keys. 
# The brief says "SEUL accounts_service génère le JWT", "Les autres... Vérifient le JWT via JWTAuthentication".
# For HS256 to work, they need the same secret key.
# The `settings.py` for adoption uses a different SECRET_KEY by default from startproject. 
# We should ideally use the same key or a shared env var.
# I will set the signing key to be configurable via env or use the one from accounts if hardcoded (not recommended but likely for this level).
# Wait, let's look at accounts settings again. "django-insecure-!%@s%_+o8+c5y1ooxx6y+3j67^3+76iroo67lxc43f5qj41l$a"
# Adoption has: "django-insecure-!e^$%sa!34yzt^+3orbinabf4@n+b&8-w^+ly5$sm@ff6evkuo"
# THEY MUST MATCH for HS256. I will add a comment or update it. 
# Since I cannot easily change the user's environment variables, I will hardcode the key from accounts_service here 
# to Ensure it works, or better, simply rely on `SIMPLE_JWT` default utilizing `SECRET_KEY` and set `SECRET_KEY` to be the same.
# Or better, explicit SIMPLE_JWT config.

SIMPLE_JWT = {
    'SIGNING_KEY': 'django-insecure-!%@s%_+o8+c5y1ooxx6y+3j67^3+76iroo67lxc43f5qj41l$a', # MATCHING ACCOUNTS SERVICE
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Sync with accounts_service
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_CLAIM': 'user_id',
}

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

TRAEFIK_BASE_URL = "http://localhost:80"

# Consul / Service Configuration
CONSUL_HOST = 'localhost'
CONSUL_PORT = 8500
SERVICE_NAME = 'adoption-service'
SERVICE_ID = 'adoption-1'
SERVICE_PORT = 8003


# Removed Session/Cookies stuff as it is strictly Forbidden
# SESSION_ENGINE = ...


ACCOUNTS_SERVICE_URL = "http://127.0.0.1:8001"