# Generated by Django 5.2.8 on 2025-12-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_submitted_by_user_alter_animal_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'permissions': [('can_publish_animal', 'Can publish animal'), ('can_approve_animal', 'Can approve animal')]},
        ),
    ]
