# Generated by Django 5.2.8 on 2025-12-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_animal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
    ]
