# Image de base Python légère
FROM python:3.11-slim

# Dossier de travail dans le container
WORKDIR /app

# Copier les dépendances
COPY requirements.txt .

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code du microservice
COPY . .

# Exposer le port du microservice (8004 pour notifications)
EXPOSE 8004

# Commande pour lancer Django (serveur web du microservice)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8004"]
